### ISSUE TITLE
TESTING: Demo/Large Explore Visual

### ISSUE THREAD

**Issue by gjwgit** [gjwgit/rattle#340]

**Comment by junhaow1** [comment]
https://github.com/gjwgit/rattleng/pull/366/files PR created

**Comment by junhaow1** [comment]
<img width="1212" alt="image" src="https://github.com/user-attachments/assets/568e56f9-ac17-456c-b8b7-bbb423708347">

**Comment by junhaow1** [comment]
- [x] Large done
- [ ] No need to test the demo dataset because it does not have a valid "Variable" to generate visual analysis 
<img width="628" alt="image" src="https://github.com/user-attachments/assets/3175dac6-a0b7-4113-a34c-4cf04872dc0c">

**Comment by gjwgit** [comment]
Thanks @junhaow1 I am seeing he following when I load the DEMO dataset? What is the scenario that you do not get a valid variable for DEMO?

![Image](https://github.com/user-attachments/assets/4660e45f-3e3b-4e4f-8cdc-5c8132570993)

**Comment by gjwgit** [comment]
If I run `make explore_visual_large.itest` it works okay but when I run `make explore_visual_large.quest` it is failing:



![Image](https://github.com/user-attachments/assets/3604ce22-702a-4b62-8f23-3ac20883adf4)

```
03 Sep 08:46:27 gjw@kadesh ~/projects/rattleng$ make explore_visual_large.qtest
00:00 +0: ...gjw/git/github/gjwgit/rattleng/integration_test/explore_visual_large_test.dart     B00:08 +0: ...gjw/git/github/gjwgit/rattleng/integration_test/explore_visual_large_test.dart     
✓ Built build/linux/x64/debug/bundle/rattle
00:10 +0: Explore tab Large dataset: Visual feature.                                            
R START                  main.R
R LOAD                   integration_test/rattle_test_large.csv
R SOURCE                 dataset_load_csv.R
R SOURCE                 dataset_prep.R
R SOURCE                 dataset_glimpse.R
R LOADED                 integration_test/rattle_test_large.csv
R SOURCE                 dataset_template.R
  BUILD                  ExploreTab
ERROR: unidentified variables: rec_id!
ERROR: unidentified variables: ssn!
ERROR: unidentified variables: first_name!
ERROR: unidentified variables: middle_name!
ERROR: unidentified variables: last_name!
ERROR: unidentified variables: gender!
ERROR: unidentified variables: age_at_consultation!
ERROR: unidentified variables: birth_date!
ERROR: unidentified variables: medicare_number!
ERROR: unidentified variables: street_address!
ERROR: unidentified variables: suburb!
ERROR: unidentified variables: postcode!
ERROR: unidentified variables: state!
ERROR: unidentified variables: phone!
ERROR: unidentified variables: email!
ERROR: unidentified variables: marital_status!
ERROR: unidentified variables: height!
ERROR: unidentified variables: weight!
ERROR: unidentified variables: bmi!
ERROR: unidentified variables: blood_pressure!
ERROR: unidentified variables: cholesterol_level!
ERROR: unidentified variables: smoking_status!
ERROR: unidentified variables: clinical_notes!
ERROR: unidentified variables: consultation_timestamp!
  BUILD                  ActivityButton
R SOURCE                 explore_visual_categoric.R
ERROR: unidentified variables: rec_id!
ERROR: unidentified variables: ssn!
ERROR: unidentified variables: first_name!
ERROR: unidentified variables: middle_name!
ERROR: unidentified variables: last_name!
ERROR: unidentified variables: gender!
ERROR: unidentified variables: age_at_consultation!
ERROR: unidentified variables: birth_date!
ERROR: unidentified variables: medicare_number!
ERROR: unidentified variables: street_address!
ERROR: unidentified variables: suburb!
ERROR: unidentified variables: postcode!
ERROR: unidentified variables: state!
ERROR: unidentified variables: phone!
ERROR: unidentified variables: email!
ERROR: unidentified variables: marital_status!
ERROR: unidentified variables: height!
ERROR: unidentified variables: weight!
ERROR: unidentified variables: bmi!
ERROR: unidentified variables: blood_pressure!
ERROR: unidentified variables: cholesterol_level!
ERROR: unidentified variables: smoking_status!
ERROR: unidentified variables: clinical_notes!
ERROR: unidentified variables: consultation_timestamp!
  BUILD                  ActivityButton
ERROR: unidentified variables: rec_id!
ERROR: unidentified variables: ssn!
ERROR: unidentified variables: first_name!
ERROR: unidentified variables: middle_name!
ERROR: unidentified variables: last_name!
ERROR: unidentified variables: gender!
ERROR: unidentified variables: age_at_consultation!
ERROR: unidentified variables: birth_date!
ERROR: unidentified variables: medicare_number!
ERROR: unidentified variables: street_address!
ERROR: unidentified variables: suburb!
ERROR: unidentified variables: postcode!
ERROR: unidentified variables: state!
ERROR: unidentified variables: phone!
ERROR: unidentified variables: email!
ERROR: unidentified variables: marital_status!
ERROR: unidentified variables: height!
ERROR: unidentified variables: weight!
ERROR: unidentified variables: bmi!
ERROR: unidentified variables: blood_pressure!
ERROR: unidentified variables: cholesterol_level!
ERROR: unidentified variables: smoking_status!
ERROR: unidentified variables: clinical_notes!
ERROR: unidentified variables: consultation_timestamp!
  BUILD                  ActivityButton
ERROR: unidentified variables: rec_id!
ERROR: unidentified variables: ssn!
ERROR: unidentified variables: first_name!
ERROR: unidentified variables: middle_name!
ERROR: unidentified variables: last_name!
ERROR: unidentified variables: gender!
ERROR: unidentified variables: age_at_consultation!
ERROR: unidentified variables: birth_date!
ERROR: unidentified variables: medicare_number!
ERROR: unidentified variables: street_address!
ERROR: unidentified variables: suburb!
ERROR: unidentified variables: postcode!
ERROR: unidentified variables: state!
ERROR: unidentified variables: phone!
ERROR: unidentified variables: email!
ERROR: unidentified variables: marital_status!
ERROR: unidentified variables: height!
ERROR: unidentified variables: weight!
ERROR: unidentified variables: bmi!
ERROR: unidentified variables: blood_pressure!
ERROR: unidentified variables: cholesterol_level!
ERROR: unidentified variables: smoking_status!
ERROR: unidentified variables: clinical_notes!
ERROR: unidentified variables: consultation_timestamp!
  BUILD                  ActivityButton
══╡ EXCEPTION CAUGHT BY FLUTTER TEST FRAMEWORK ╞════════════════════════════════════════════════════
The following TestFailure was thrown running a test:
Expected: exactly one matching candidate
  Actual: _TextContainingWidgetFinder:<Found 0 widgets with text containing Density Plot of Values:
[]>
   Which: means none were found but one was expected

When the exception was thrown, this was the stack:
#4      main.<anonymous closure>.<anonymous closure> (file:///home/gjw/git/github/gjwgit/rattleng/integration_test/explore_visual_large_test.dart:155:7)
<asynchronous suspension>
#5      testWidgets.<anonymous closure>.<anonymous closure> (package:flutter_test/src/widget_tester.dart:189:15)
<asynchronous suspension>
#6      TestWidgetsFlutterBinding._runTestBody (package:flutter_test/src/binding.dart:1032:5)
<asynchronous suspension>
<asynchronous suspension>
(elided one frame from package:stack_trace)

This was caught by the test expectation on the following line:
  file:///home/gjw/git/github/gjwgit/rattleng/integration_test/explore_visual_large_test.dart line 155
The test description was:
  Visual feature.
════════════════════════════════════════════════════════════════════════════════════════════════════
00:18 +0 -1: Explore tab Large dataset: Visual feature. [E]                                     
  Test failed. See exception logs above.
  The test description was: Visual feature.
  

To run this test again: /home/gjw/development/flutter/bin/cache/dart-sdk/bin/dart test /home/gjw/git/github/gjwgit/rattleng/integration_test/explore_visual_large_test.dart -p vm --plain-name 'Explore tab Large dataset: Visual feature.'
00:18 +0 -1: Some tests failed.                                                                 
make: *** [support/flutter.mk:276: explore_visual_large.qtest] Error 1
```

**Comment by gjwgit** [comment]
I think I see the issue. The delay is set to be 5s rather than the otherwise default 1s. I might replace this with the hack delay instead to highlight this is a bug that needs fixing.

I still don't know why the DEMO one would not work though?

**Comment by gjwgit** [comment]
I updated `integration_test/explore_visual_large_test.dart` to use `openLargeDataset()`. That works.

Could you provide a `integration_test/explore_visual_demo_test.dart`. We have to get that working.

Also need to think about how to verify the images.

**Comment by gjwgit** [comment]
Once we have integration_test/explore_visual_demo_test.dart we can close this.

**Comment by junhaow1** [comment]
<img width="647" alt="image" src="https://github.com/user-attachments/assets/378cea55-b578-43dc-9547-17bab4a78ac9">

**Comment by gjwgit** [comment]
The default is:

![image](https://github.com/user-attachments/assets/9db04746-c54f-4121-9d62-3532968e1fde)

That works to produce:

![image](https://github.com/user-attachments/assets/816e0e71-fda8-488d-a147-842e6d909fe2)

If you change to wind_dir_3pm (as your should in the test also, in addition to the above) then that works too:

![image](https://github.com/user-attachments/assets/49a98f70-0f20-40fe-a665-367cbc164d4e)

**Comment by junhaow1** [comment]
https://github.com/gjwgit/rattleng/pull/383 PR created

**Comment by junhaow1** [comment]
> rather than the otherwise default 1s. I might replace this with the hack delay instead to highlight this is a bug that needs fixing.
> 
> I still don't know why the DEMO one would not work though?

Fixed, PR created

**Comment by gjwgit** [comment]
Tested and working. Thanks.
