### ISSUE TITLE
EXCEPTION: Duplicate GlobalKey detected in widget tree

### ISSUE THREAD

**Issue by gjwgit** [gjwgit/rattle#388]
DEMO -> EXPLORE -> SUMMARY -> VISUAL

Without any BUILD buttons I end up with the following exception. Seems to occur in numerous places when moving from one FEATURE to another. Is this to do with adding keys for the testing?

```
══╡ EXCEPTION CAUGHT BY WIDGETS LIBRARY ╞═══════════════════════════════════════════════════════════
The following assertion was thrown while finalizing the widget tree:
Duplicate GlobalKey detected in widget tree.
The following GlobalKey was specified multiple times in the widget tree. This will lead to parts of
the widget tree being truncated unexpectedly, because the second time a key is seen, the previous
instance is moved to the new location. The key was:
- [LabeledGlobalKey<PagesState>#4edfd]
This was determined by noticing that after the widget with the above global key was moved out of its
previous parent, that previous parent never updated during this frame, meaning that it either did
not update at all or updated before the widget was moved, in either case implying that it still
thinks that it should have a child with that global key.
The specific parent that did not update after having one or more children forcibly removed due to
GlobalKey reparenting is:
- SummaryDisplay(dependencies: [UncontrolledProviderScope], state: _SummaryDisplayState#657dc)
A GlobalKey can only be specified on one widget at a time in the widget tree.

When the exception was thrown, this was the stack:
#0      BuildOwner.finalizeTree.<anonymous closure> (package:flutter/src/widgets/framework.dart:3317:15)
#1      BuildOwner.finalizeTree (package:flutter/src/widgets/framework.dart:3342:8)
#2      WidgetsBinding.drawFrame (package:flutter/src/widgets/binding.dart:1169:19)
#3      RendererBinding._handlePersistentFrameCallback (package:flutter/src/rendering/binding.dart:468:5)
#4      SchedulerBinding._invokeFrameCallback (package:flutter/src/scheduler/binding.dart:1397:15)
#5      SchedulerBinding.handleDrawFrame (package:flutter/src/scheduler/binding.dart:1318:9)
#6      SchedulerBinding._handleDrawFrame (package:flutter/src/scheduler/binding.dart:1176:5)
#7      _invoke (dart:ui/hooks.dart:312:13)
#8      PlatformDispatcher._drawFrame (dart:ui/platform_dispatcher.dart:419:5)
#9      _drawFrame (dart:ui/hooks.dart:283:31)
════════════════════════════════════════════════════════════════════════════════════════════════════
```

**Comment by zheyxu** [comment]
Made pr https://github.com/gjwgit/rattleng/pull/396
