### ISSUE TITLE
ASSOCIATIONS: model_arules_viz.svg not rendering in Flutter

### ISSUE THREAD

**Issue by gjwgit** [gjwgit/rattle#728]
## Description

MOVIES -> MODEL -> ASSOCIATIONS -> BUILD -> PAGE 5

![Image](https://github.com/user-attachments/assets/c3698658-c861-435b-9f54-b61d353023cd)

```
══╡ EXCEPTION CAUGHT BY IMAGE RESOURCE SERVICE ╞════════════════════════════════════════════════════
The following _Exception was thrown resolving an image codec:
Exception: Invalid image data

When the exception was thrown, this was the stack:
#0      _futurize (dart:ui/painting.dart:7324:5)
#1      ImageDescriptor.encoded (dart:ui/painting.dart:7130:12)
#2      instantiateImageCodecWithSize (dart:ui/painting.dart:2471:60)
#3      PaintingBinding.instantiateImageCodecWithSize (package:flutter/src/painting/binding.dart:147:15)
#4      MemoryImage._loadAsync (package:flutter/src/painting/image_provider.dart:1602:18)
<asynchronous suspension>
#5      MultiFrameImageStreamCompleter._handleCodecReady (package:flutter/src/painting/image_stream.dart:1013:3)
<asynchronous suspension>
════════════════════════════════════════════════════════════════════════════════════════════════════
```

Yet it displays just fine with the PopOut of the image.

![Image](https://github.com/user-attachments/assets/2cfcf6fa-255d-4266-950d-08e3cfd63088)

**Comment by gjwgit** [comment]
Document the code to indicate this issue with flutter_svg not supporting the filter element.
